version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map frontend port to host
    depends_on:
      - backend # Ensure backend starts first
    environment:
      - REACT_APP_API_URL=http://localhost:9000 # Pass API URL to frontend
    
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9000:9000" # Map backend port to host
  #   environment:
  #     - DB_HOST=localhost
  #     - DB_USER=root
  #     - DB_PASSWORD=rootpassword
  #     - DB_NAME=tododatabase
  #   depends_on:
  #     - database # Ensure database starts first

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=tododatabase
    depends_on:
      - database


  database:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tododatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
